### ISSUE TITLE
undefined symbol: hts_utell

### ISSUE THREAD

**Issue by RADIOMUMM** [ShujiaHuang/basevar#12]
I use the commad ""/usr/bin/basevar" -h",but it dosnt work !

return me "undefined symbol: hts_utell"

whole waring:
Traceback (most recent call last):
  File "/usr/bin/basevar", line 9, in <module>
    load_entry_point('basevar==0.8.0', 'console_scripts', 'basevar')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib64/python2.7/site-packages/basevar/runner.py", line 13, in <module>
    from caller.executor import BaseTypeRunner
  File "basevar/caller/executor.pyx", line 1, in init basevar.caller.executor
    """
  File "basevar/io/fasta.pyx", line 8, in init basevar.io.fasta
    from basevar.io.openfile import Open
  File "basevar/io/openfile.pyx", line 11, in init basevar.io.openfile
    from basevar.io.BGZF.bgzf import BGZFile
  File "basevar/io/BGZF/bgzf.pyx", line 1, in init basevar.io.BGZF.bgzf
    # cython: embedsignature=True
ImportError: /usr/lib64/python2.7/site-packages/basevar/io/htslibWrapper.so: undefined symbol: hts_utell

**Comment by xiaoliangtian** [comment]
hi, i had the same problem. please tell me how it was finally resolved.

**Comment by RADIOMUMM** [comment]
hi
  i give up this software!
  You can try this [BaseVarC](https://github.com/Zilong-Li/BaseVarC)

**Comment by RADIOMUMM** [comment]
> hi, i had the same problem. please tell me how it was finally resolved.
hi
i give up this software!
You can try this [BaseVarC](https://github.com/Zilong-Li/BaseVarC)

**Comment by Sondr11** [comment]
@RADIOMUMM 
Can you help me how to install BaseVarC?

**Comment by RADIOMUMM** [comment]
> @RADIOMUMM Can you help me how to install BaseVarC?

move to BaseVarC github page ([BaseVarC](https://github.com/Zilong-Li/BaseVarC))

git clone --recursive https://github.com/Zilong-Li/BaseVarC.git
cd BaseVarC
./configure
make

**Comment by Sondr11** [comment]
Hi @RADIOMUMM 
I installed and run  test success. Now I will run for sample, Hope it's OK.
Beside,can you guide me how to interpret these millions of variants as pathogenic, benign or like begin?
Thank you so much
